### ISSUE TITLE
python 3.x compatible

### ISSUE THREAD

**Issue by vlordier** [synw/django-instant#1]
There are a few print which require () for instant to run smoothly with python 3.x

**Comment by synw** [comment]
Corrected, thanks: https://github.com/synw/django-instant/commit/239bea8ff6b09ffc3668e35c09e2480946c14731

I must admit I don't know python 3. Please let me know if it works now, and then I'll close the issue and release.

**Comment by vlordier** [comment]
the prints are working, other than that it works

**Comment by synw** [comment]
I released version 0.2 that is now python 3 compatible thanks to you.
