### ISSUE TITLE
Could not custumize messages handlers

### ISSUE THREAD

**Issue by tboulogne** [synw/django-instant#13]
Hello,

Could you explain how to customize this handlers please ? Look into documentation and try to apply but did not works.

Note : debug works fine.

Thanks for help.

Regards,

Thierry

**Comment by synw** [comment]
Hi. I rewrote the docs to make it more clear. It was a bit messy yes, specially the client side handlers: this should be better now. Thanks for mentioning it.

Please check out the [client side handlers](http://django-instant.readthedocs.io/en/latest/src/handle_messages.html) part and let me know if anything is unclear or wrong anymore

**Comment by tboulogne** [comment]
hello,

My template directory is like this

```
templates
 I_ instant
    I_ handlers
       I- default.js
```
Into default.js i get : 
```
if (channel === "public") {
    console.log(message)
 }
```

But nothing into console.log. I enable watch option on instant admin, i could see messages.

Any idea please ?

**Comment by synw** [comment]
The default public channel name is `settings.SITE_SLUG_public`, so if your `SITE_SLUG` value in settings is `my_site`, your channel will be named `mysite_public`.
You can check in the debug console for the connected channels. Note: it is better to use declarative channels: it is more explicit and you can even control where it should connect from. In settings, and the default public channel will be deprecated in the future

```python
INSTANT_ENABLE_PUBLIC_CHANNEL = False  # do not use the default chan
# declare my chan
INSTANT_PUBLIC_CHANNELS = [
    ['public_chan'],
]
```
Then use a `templates/instant/handlers/public_chan.js` handler, or just stick with the default handler

I plan to work on better error messages btw,

{Edit]: 
> I enable watch option on instant admin, i could see messages.

Check the channel name in the json console message to make sure it is ok

{Edit 2]

> nothing into console.log

Did you set the `INSTANT_DEBUG` setting to True? It should show you if you are connected on a channel or not. Did you include the client template?

**Comment by tboulogne** [comment]
my bad again !
In my different tests to make it work i remove the client.

Thanks i'm on the way now ;).

**Comment by synw** [comment]
That's it! Enjoy
