### ISSUE TITLE
Channels handlers

### ISSUE THREAD

**Issue by tboulogne** [synw/django-instant#14]
Hello,

I put a default.js handler working well.
I create a staff channel (**$mysite_staff1**). Create the appropriate handler (**$mysite_staff1.js**).

It does not work ?

Note debug :
```
No handlers found for custom channels
```

any idea please ?

**Comment by synw** [comment]
Try to restart the dev server after adding a new handler template: it is required for the template to be found. I should mention this in the doc

Then you can verify that the handler appears in the `Handlers` list in the python console in debug mode

This can be an error in the file name: the message means there is a `FileNotFoundError`

**Comment by tboulogne** [comment]
Several restait later, only get in debug :

No handlers found for custom channels :-(

**Comment by synw** [comment]
This error means that it can't find the handlers dir. It is caused by this code (in apps.py) used to initialize the module:

```python
d = "templates/instant/handlers"
handlers_dir = safe_join(settings.BASE_DIR, d)
# map default handlers
handlers = os.listdir(handlers_dir)
```
Is your `settings.BASE_DIR` set?

Try to run this code in the console to get the error. I can't throw an exception here because the handler dir is optional

**Comment by tboulogne** [comment]
Yes it is :

**Comment by tboulogne** [comment]
ok get it.

You need to deal with app templates(templates directory into APP)  or project template (template into project root).

Mine is an app template folder. So BASE_DIR is incomplete for it.

**Comment by synw** [comment]
I see. Yes it searches for the project templates directory and this does not work for an app template dir. Maybe there would be a way to lookup in app templates folders but I don't know how to do it in a clean way yet.
I'll keep this in mind and try to find a way when I have a bit of time: this would be required for the new database channels actually in development. Thanks for making me realize this.

**Comment by tboulogne** [comment]
best approach could be looking into TEMPLATES[0]['DIRS']

**Comment by synw** [comment]
Yep this looks clean: will try to implement, thanks

**Comment by tboulogne** [comment]
something like :
```
if not os.path.isdir(handlers_dir):
                if settings.TEMPLATES and TEMPLATES[0]['DIRS']:
                    dirs = TEMPLATES[0]['DIRS']
                    for dir in dirs:
                        handlers_check = safe_join(dir, d)
                        if os.path.isdir(handlers_check):
                            handlers_dir = handlers_check
                            break
```
