### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by KakarN** [synw/django-instant#22]
I have installed django-instant, and since I am using ubuntu 18.04, I have downloaded centrifugo vv1.8.0 in my django project folder, unzipped it and ran the `./centrifugo genconfig` command. After which I can successfully run centrifugo server.

```
./centrifugo --config=config.json

[I]: 2019/02/09 04:54:35 Config path: /vagrant/instant_server/centrifugo-1.8.0-linux-amd64/config.json
[I]: 2019/02/09 04:54:35 Version: 1.8.0
[I]: 2019/02/09 04:54:35 PID: 1348
[I]: 2019/02/09 04:54:35 Engine: In memory – single node only
[I]: 2019/02/09 04:54:35 GOMAXPROCS: 1
[I]: 2019/02/09 04:54:35 SockJS url: //cdn.jsdelivr.net/sockjs/1.1/sockjs.min.js
[I]: 2019/02/09 04:54:35 Start serving raw websocket, SockJS, API endpoints on :8000
```

In the django project settings I have added:

```
MIDDLEWARE = [
   ...
   'corsheaders.middleware.CorsMiddleware',
   'django.middleware.common.CommonMiddleware',
   ...
]

# required settings
CENTRIFUGO_SECRET_KEY = "fe3ad3c2-41ce-4d7c-8034-a42a1a3569d3" # updated the key generated in config.json
SITE_SLUG = "my_site" # used internaly to prefix the channels
SITE_NAME = "My site"

CORS_ORIGIN_WHITELIST = ('localhost:8001',)

# optionnal settings
# CENTRIFUGO_HOST = 'http://ip_here' #default: localhost
CENTRIFUGO_PORT = 8000 # default: 8001
# CENTRIFUGO_PROXY = True # default: False - remove port from URL if you are behind a proxy.
```

And to test the frontend example, I have installed the package `pip install django-vitevue`. And have added the required apps into the settings.py and urls.py:

```
# settings.py
INSTALLED_APPS = [
    ...
    "corsheaders",
    "instant",
    "vv",
]

# urls.py
urlpatterns = [
     # ...
     url(r'^centrifuge/auth/$', instant_auth, name='instant-auth'),
     url('^instant/', include('instant.urls')),
     ]
```

Finally, I ran the django server and centrifugo server separately on different terminals, and both are running properly.

After I logged in as superuser, opened up two separate browser tab, go to the /instant/ URL and go the mysite channel. But after I send a message, there is no message in either of the browser tabs.

Can you please help me figure out what's wrong? If it helps, the ubuntu server is working on a vagrant machine.

**Comment by synw** [comment]
Your config looks good. Try the `INSTANT_DEBUG = true` setting and run the stuff: what does the javascript console say?

**Comment by KakarN** [comment]
Ok, what I thought since django-instant and centrifugo was on the same machine, they would communicate within localhost. But I guess, the `CENTRIFUGO_HOST` setting is for the client side. ( @synw Am I right on this?)

So I had to set the host address to my vagrant machine's, and it works now.

`CENTRIFUGO_HOST = 'http://192.168.33.10'`

**Comment by synw** [comment]
> I guess, the CENTRIFUGO_HOST setting is for the client side. ( @synw Am I right on this?

Yes it is used to connect from the js
