### ISSUE TITLE
running the python3 manage.py installws throws this error

### ISSUE THREAD

**Issue by mcroni** [synw/django-instant#23]
`  File "/root/centr/lib/python3.5/site-packages/django/template/backends/django.py", line 121, in get_package_libraries
    module = import_module(entry[1])
  File "/root/centr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/root/centr/lib/python3.5/site-packages/instant/templatetags/instant_tags.py", line 14, in <module>
    SECRET_KEY = getattr(settings, 'CENTRIFUGO_SECRET_KEY')
  File "/root/centr/lib/python3.5/site-packages/django/conf/__init__.py", line 80, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'CENTRIFUGO_SECRET_KEY'`

**Comment by synw** [comment]
It seems that something has changed in the way that Django imports modules in the management command, causing this error. This will probably mean having to configure the settings manually before running this command. If you configure your settings manually it will work

Note: this module is not active today because I do not need it anymore and Centrifugo has released a version 2 with a lot of changes which would mean big work here to update. So it is outdated today even if it still work.

**Comment by mcroni** [comment]
didnt use the installws anymore, i used the manual installation, followed the docs and added the include tag to the html codes and made sure i had corsheaders and instant in my settings file but i get this error `vv_tags' is not a registered tag library. Must be one of:`

**Comment by synw** [comment]
Try following theses steps : https://django-instant.readthedocs.io/en/latest/src/install.html#frontend

**Comment by mcroni** [comment]
got myself a VPS from DO and ive got centrifugo beautifully installed on ubuntu bionic,
`
Aug 17 19:20:15 raedarr systemd[1]: Stopped Centrifugo real-time messaging server.
{"level":"info","time":"2019-08-17T19:20:16Z","message":"serving websocket, SockJS, API endpoints on :8000"}
`
But i cant connect to the ws server, i get this from the console of chrome `https://xxxxxxxxx:8000/connection/info?t=1566102911694 net::ERR_SSL_PROTOCOL_ERROR`

Now, my issues is the server is telling me that its running on port 8000 but  the docs says we should port it out to different ports here
`
CORS_ORIGIN_WHITELIST = ('localhost:8001',)

CENTRIFUGO_HOST = 'http://ip_here' #default: localhost
CENTRIFUGO_PORT = 8012 # default: 8001
CENTRIFUGO_PROXY = True # default: False - remove port from URL if you are behind a proxy
`

**Comment by synw** [comment]
Note: this module was written for Centrifugo 1 and does not work with Centrifugo 2. This is why it is deprecated now. About the proxy I never used this feature so I am not sure. I can't fix this as this module is now deprecated sorry

**Comment by synw** [comment]
Version 2 is now compatible with Centrifugo 2
