### ISSUE TITLE
Handle the events in Python-side.

### ISSUE THREAD

**Issue by Kinzowa** [synw/django-instant#24]
Hello,

I really like the idea of this library but still scratching my head to figure out how to handle the events in Python. Could you please elaborate more on this ? What I would like to do is creating bi-directional communication channels between Django projects.

Thank you

**Comment by synw** [comment]
Hi. To listen to the messages on a channel from server side is not easy as async is not available in Django. But you can do it using a [publish proxy](https://centrifugal.dev/docs/3/server/proxy#publish-proxy) : Centrifugo will forward the events to the backend before publication. There is a [Django example that implements this](https://centrifugal.dev/blog/2021/11/04/integrating-with-django-building-chat-application#implementing-proxy-handlers)

**Comment by Kinzowa** [comment]
Thanks for pointing me the links, much appreciated.
