### ISSUE TITLE
Updates for centrifugo v4

### ISSUE THREAD

**Issue by 55nevets** [synw/django-instant#25]
Is this package actively maintained?  A new release to centrifugo v4 came out in July 2022.  Latest update is Mar 2022.

**Comment by synw** [comment]
Yes I should update it for the latest Centrifugo version when I find the time to. Is it actually broken on Centrifugo 4?

**Comment by synw** [comment]
I release the[ 4.0.1 version](https://github.com/synw/django-instant/releases/tag/4.0.1) with Centrifugo 4 support
