### ISSUE TITLE
AttributeError at /instant/login/  'User' object has no attribute 'is_superuser'

### ISSUE THREAD

**Issue by thewhisperinyourears** [synw/django-instant#31]
I am trying to use django-instant but I am getting this problem. I am using the superuser account.

```
Traceback (most recent call last):
  File "C:\instant\views.py", line 55, in login_and_get_tokens
    return _get_response(request)
  File "C:\instant\views.py", line 41, in _get_response
    channels = user_channels(request.user)
  File "C:\instant\views.py", line 12, in user_channels
    user_chans = Channel.objects.for_user(user)
  File "C:\instant\models.py", line 11, in for_user
    if user.is_superuser:

Exception Type: AttributeError at /instant/login/
Exception Value: 'User' object has no attribute 'is_superuser'
```

**Comment by synw** [comment]
Are you using a custom user model? Does you user model have the `is_superuser` and `is_staff` properties?

**Comment by thewhisperinyourears** [comment]
Yes I have a custom Model which extends AbstractBaseUser. I added the is_superuser property and now is getting beyond that but I encountered a new error.

'User' object has no attribute 'groups'

**Comment by thewhisperinyourears** [comment]
Nevermind I added groups to my custom user model. Let me know if this is wrong. I can see the ws_token etc now. So I think this is working.
`    groups = models.ManyToManyField(Group, blank=True, verbose_name=_("Groups"))`

**Comment by thewhisperinyourears** [comment]
Does django-instant works with django 4 and centrifugo 4?

**Comment by synw** [comment]
We have Centrifugo 4 support since https://github.com/synw/django-instant/releases/tag/4.0.1 and it works with Django 4 yes
