### ISSUE TITLE
Typo in centrifugo connection error go process

### ISSUE THREAD

**Issue by mbeacom** [synw/django-instant#4]
There seems to be a typo in:
[`fmt.Sprintf("Centrifugo client error: %s", err.Error())`](https://github.com/synw/django-instant/blob/master/instant/go/src/main.go#L36)

**Comment by synw** [comment]
Thank you. Yes this file needed some cleaning and linting: it is old code. I should btw replace `broadcast` by `publish` to match with Centrifugo's terminology

Could you please post a PR so that I can merge your corrections?

**Comment by mbeacom** [comment]
I went ahead and modified `broadcast` to `publish` in the go app, but I held off on renaming the binary and proc call to the binary.

I'll submit a separate PR for touching the `producers.py` file.

**Comment by synw** [comment]
I made the change to `producers.py` and renamed the binary. Thanks for your contribution.
